# (Defined host vars (inventory))
# hostname: temporary-hostname
# hardware:
#   disk_name: /dev/sdX
# user:
#   name: raphiz
#   uid: 1000
#   group: raphiz
#   password: 12345
#   password_salt: 12345
# features:
#  - resticTimer
#  - cnijfilter2
#  - virtualbox

# Global packages
base_packages:
  - base
  - reflector
  - pacman-contrib
  - vim
  - git
  - zsh
  - fasd
  - python
  - python-pip
  - openssh
  - unzip
  - zip
  - fd
  - bat
  - ripgrep
  - httpie
  - tree

desktop_apps:
  base:
    - firefox
    - thunderbird
    - thunar
    - qpdfview
    - libreoffice-fresh-de
    - ntfs-3g
    - jq
    - qalculate-gtk
  graphic:
    - gimp
    - inkscape
    - maim
    - imagemagick
  media:
    - vlc
    - audacious
  sytem:
    - wget
    - htop
    - gparted
    - sshfs
    - shellcheck
    - diffuse
    - pacmatic

desktop_apps_aur:
  base:
    - name: google-chrome
      hash: 4e2518c2cb5802cd49fd0a2bb83180320d4100cd
    - name: direnv
      hash: 22ec859e0ae62744acf9658110aad765ece3444e
    - name: autojump
      hash: 22b96ef925fe122bfa374138442f031e10de138c
    - name: protonmail-bridge
      hash: 7a2a4cd904a7406b19446e0fed930dd13ab36fc7
    - name: notable-bin
      hash: 409df4079669883feb4bcaa1b4b7a9b675fe7d96
    - name: intellij-idea-ultimate-edition
      hash: 88b7549c433a7a2fbc9c6a3a17387f76e0e7bf98
    - name: nvm
      hash: 98091c0759162b1032722896d7443530151ab9c8

# To update this list, use `code --list-extensions`
vscode_extensions:
  - ms-python.python
  - ms-vscode.vscode-typescript-tslint-plugin
  - DavidAnson.vscode-markdownlint
    # - adamvoss.vscode-languagetool
    # - adamvoss.vscode-languagetool-de
    # - adamvoss.vscode-languagetool-en
  - esbenp.prettier-vscode
    # - mikeburgh.xml-format
  - octref.vetur
  - coolbear.systemd-unit-file
  - streetsidesoftware.code-spell-checker
  - streetsidesoftware.code-spell-checker-german
  - timonwong.shellcheck
  - foxundermoon.shell-format
  - dhoeric.ansible-vault
  - vscoss.vscode-ansible
  - CoenraadS.bracket-pair-colorizer-2
  - EditorConfig.EditorConfig
    # - VisualStudioExptTeam.vscodeintellicode
  - redhat.vscode-yaml
  - ms-azuretools.vscode-docker
  - msjsdiag.debugger-for-chrome
  - exiasr.hadolint
# - joaompinto.asciidoctor-vscode
# - stayfool.vscode-asciidoc

dotfiles: git://github.com/Excape/dotfiles.git

journal:
  max_size: 500M

base_fonts:
  - terminus-font
  - ttf-dejavu
  - ttf-bitstream-vera
  - ttf-liberation
  - gsfonts
  - tex-gyre-fonts
  - noto-fonts-emoji
  - noto-fonts-cjk
  - ttf-fira-mono
  - ttf-fira-code
  - ttf-opensans
  - ttf-roboto
  - ttf-roboto-mono
  - ttf-ubuntu-font-family

aur_fonts:
  # TODO: Temporarliy disabled since sources are currently unavailable
  # - name: ttf-symbola
  #   hash: 657659284c461b1afb259e777329a391153e7550
  - name: ttf-windows
    hash: e61fd6492fa0e94b4918778e7f5ec3bca9f2525a
  - name: ttf-ms-fonts
    hash: 4b3621d776c7090b7d42ff53e1aa0170e16477e5
  - name: nerd-fonts-hack
    hash: 570d51794e8964564c674b5a6d80db3f4f336db0
