# (Defined host vars (inventory))
# hostname: temporary-hostname
# hardware:
#   disk_name: /dev/sdX
# user:
#   name: raphiz
#   uid: 1000
#   group: raphiz
#   password: 12345
#   password_salt: 12345
# features:
#  - resticTimer
#  - cnijfilter2
#  - virtualbox

# Global packages
base_packages:
  - base
  - reflector
  - pacman-contrib
  - vim
  - git
  - python
  - python-pip
  - openssh
  - unzip
  - zip
  - fd
  - bat
  - ripgrep
  - httpie

desktop_apps:
  base:
    - firefox
    - thunderbird
    - notepadqq
    - qpdfview
    - libreoffice-fresh-de
    - hunspell
    - hunspell-de
    - autojump
    - keepassxc
    - ntfs-3g
    - jq
  graphic:
    - gimp
    - inkscape
    - imagemagick
  media:
    - vlc
    - audacious
  sytem:
    - wget
    - htop
    - gparted
    - sshfs
    - shellcheck
    - diffuse
    - pacmatic

desktop_apps_aur:
  base:
    - name: google-chrome
      hash: a7c9ebaa9ae08b8e66944f610cb76a599487425b
    - name: ttf-ms-fonts
      hash: ba83093fb7e7135736d0762cceff1c264b01719c
    - name: direnv
      hash: 6f37e247d7c6b9b8f873dd53c547e4916d5df5b3

# To update this list, use `code --list-extensions`
vscode_extensions:
  - ms-python.python
  - ms-vscode.vscode-typescript-tslint-plugin
  - DavidAnson.vscode-markdownlint
  - adamvoss.vscode-languagetool
  - adamvoss.vscode-languagetool-de
  - adamvoss.vscode-languagetool-en
  - esbenp.prettier-vscode
  - mikeburgh.xml-format
  - octref.vetur
  - coolbear.systemd-unit-file
  - streetsidesoftware.code-spell-checker
  - streetsidesoftware.code-spell-checker-german
  - timonwong.shellcheck
  - dhoeric.ansible-vault
  - vscoss.vscode-ansible
  - CoenraadS.bracket-pair-colorizer-2
  - EditorConfig.EditorConfig
  - VisualStudioExptTeam.vscodeintellicode
  - redhat.vscode-yaml
  - ms-azuretools.vscode-docker
  - msjsdiag.debugger-for-chrome
# - joaompinto.asciidoctor-vscode
# - stayfool.vscode-asciidoc

dotfiles: git@github.com:raphiz/dotfiles.git

journal:
  max_size: 500M

base_fonts:
  - terminus-font
  - ttf-dejavu
  - ttf-bitstream-vera
  - ttf-liberation
  - gsfonts
  - tex-gyre-fonts
  - noto-fonts-emoji
  - ttf-fira-mono

aur_fonts:
  - name: ttf-symbola
    hash: 015b5ce0a7772a84258f040f6bb391dcad09031a
  - name: ttf-inter-ui
    hash: 59c97c0f0cebf508ff0e7be49e41e0c00e9cf829
