- name: Install RedShift
  pacman: name=redshift state=present

- name: Prepare systemd directories
  file:
    path: /home/{{ user.name }}/.config/systemd/user/default.target.wants/
    state: directory
    recurse: yes
  become: yes
  become_user: "{{ user.name }}"

- name: Enable redshift gtk service
  file:
    src: /usr/lib/systemd/user/redshift-gtk.service
    dest: /home/{{ user.name }}/.config/systemd/user/default.target.wants/redshift-gtk.service
    state: link
  become: yes
  become_user: "{{ user.name }}"
