- name: Install OpenVPN
  pacman:
    name: openvpn
    state: present
  when: features is defined and "openvpn" in features

- name: Install whois
  pacman:
    name: whois
    state: present

- name: Install netcat
  pacman:
    name: gnu-netcat
    state: present

- name: Install nmap
  pacman:
    name: nmap
    state: present

- name: Install bind-tools (formerly dnsutils)
  pacman:
    name: bind-tools
    state: present

- name: Install tcpdump
  pacman:
    name: tcpdump
    state: present

- name: Install wireshark
  pacman:
    name: wireshark-qt
    state: present

- name: Add user to wireshark group
  user:
    name: '{{ user.name }}'
    groups: wireshark
    append: yes
