- name: Check if dotfiles directory already exists
  stat:
    path: /home/{{ user.name }}/.dotfiles
  register: dotfiles_directory
  when: dotfiles is defined

- name: Clone user dotfiles
  git: repo={{ dotfiles }} dest=/home/{{ user.name }}/.dotfiles update=no
  when: dotfiles is defined and not dotfiles_directory.stat.exists
  become: yes
  become_user: "{{ user.name }}"

- name: Install user dotfiles
  command: "bash /home/{{ user.name }}/.dotfiles/install"
  when: dotfiles is defined and not dotfiles_directory.stat.exists
  become: yes
  become_user: "{{ user.name }}"
