- name: Check if dotfiles directory already exists
  stat:
    path: /home/{{ user.name }}/.dotfiles
  register: dotfiles_directory
  when: dotfiles is defined

- name: Clone user dotfiles
  git: 
    repo: "{{ dotfiles }}"
    dest: "/home/robin/.dotfiles"
    key_file: "/home/{{ user.name }}/.ssh/id_rsa"
    accept_hostkey: yes
    update: no
  when: dotfiles is defined and not dotfiles_directory.stat.exists
  become: yes
  become_user: "robin"

- name: Install user dotfiles
  command: "bash /home/{{ user.name }}/.dotfiles/install"
  when: dotfiles is defined and not dotfiles_directory.stat.exists
  become: yes
  become_user: "{{ user.name }}"
