- name: Install pulseaudio and alsa packages
  pacman:
    name:
      - pulseaudio
      - pulseaudio-alsa
      - pavucontrol
    state: present

- name: Disable PC Speaker
  copy:
    src: nobeep.conf
    dest: /etc/modprobe.d/nobeep.conf

- name: Replace pulse audio config (Automatically switch headset)
  copy:
    src: default.pa
    dest: /etc/pulse/default.pa
