- name: Install LightDM
  pacman:
    name:
      - lightdm
      - lightdm-gtk-greeter
      - light-locker
      - accountsservice
    state: present

- name: Enable LightDM
  service:
    name: lightdm.service
    enabled: yes

- name: Copy LightDM configuration
  copy:
    src: lightdm-gtk-greeter.conf
    dest: /etc/lightdm/lightdm-gtk-greeter.conf

- name: Check if accounts service user config exist for this host
  stat:
    path: hosts/files/{{inventory_hostname}}/accountsservice/{{user.name}}
  register: stat_result

- name: Copy accounts service user config
  copy:
    src: hosts/files/{{inventory_hostname}}/accountsservice/{{user.name}}
    dest: /var/lib/AccountsService/users/{{user.name}}
    mode: 0644
  when: stat_result.stat.exists


- name: Check if accounts service user icon exist for this host
  stat:
    path: hosts/files/{{inventory_hostname}}/accountsservice/{{user.name}}.png
  register: stat_result

- name: Copy accounts service user config
  copy:
    src: hosts/files/{{inventory_hostname}}/accountsservice/{{user.name}}.png
    dest: /var/lib/AccountsService/icons/{{user.name}}.png
    mode: 0755
  when: stat_result.stat.exists
