---
- name: Install universal base packages
  pacman:
    name: "{{ base_packages }}"
    state: present

- name: Create pacman hook directory
  file:
    path: /etc/pacman.d/hooks
    state: directory

- name: Push pacman mirror list update hook
  copy:
    src: mirrorlist.hook
    dest: /etc/pacman.d/hooks/mirrorlist.hook

- name: Install yay
  aur:
    name: yay
    hash: f2a571d9ee3f942af08c703d7747ccc55fa7a9df
    user: "{{ user.name }}"
